from setuptools import setup, find_packages

setup(
    name="ai-shield-kenya",
    version="0.1.0",
    description="AI Shield Kenya: A minimal, multilingual safety toolkit for Kenyan AI conversations using SIR epidemiological modeling",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="AI Shield Kenya Team",
    author_email="info@ai-shield-kenya.org",
    url="https://github.com/timo1511/ai-safety",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "numpy>=1.21.0",
        "scipy>=1.7.0",
        "pandas>=1.3.0",
        "scikit-learn>=1.0.0",
        "jupyter>=6.0.0",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Security",
        "Topic :: Education",
    ],
    keywords="ai safety, kenya, swahili, agriculture, education, misinformation",
)
